altera_data_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSGRES_HOST')}}"
      user: "{{ env_var('POSTGRES_USER')}}"
      password: "{{ env_var('POSGRES_PASSWORD')}}"
      port: "{{ env_var('POSTGRES_PORT')}}"
      dbname: "{{ env_var('DBT_DBNAME')}}"
      schema: "{{ env_var('DBT_SCHEMA')}}"
      threads: 10