version: 2

sources: 
  - name: raw
    schema: raw
    database: "{{ env_var('DBT_DBNAME')}}"
    tables:
      - name: users
        description: "Staging users from S3"
      - name: transactions
        description: "Staging transatcions from S3"